apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aryanvarma-poi-map-app-dev
  annotations:
    argocd/app-name: aryanvarma-poi-map-app-dev
    backstage.io/kubernetes-id: aryanvarma-poi-map-app
    backstage.io/kubernetes-namespace: aryanvarma
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-ms/aryanvarma-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/dev-pipelines/ns/aryanvarma/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.igb2792k.eastus2.aroapp.io/k8s/ns/aryanvarma/deployments/aryanvarma-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.igb2792k.eastus2.aroapp.io/#https://github.com/rhdh-ms/aryanvarma-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://aryanvarma-poi-map-app-aryanvarma.apps.igb2792k.eastus2.aroapp.io
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/ryanj"
  system: workshop-system-aryanvarma
  consumesApis:
    - gateway-api-aryanvarma
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-aryanvarma
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/ryanj"
